// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdE9b5x41uABm-gzPdrnKpmYnxxBYxsQ8',
    appId: '1:1037434767632:android:d27a089288df7db0ae7d95',
    messagingSenderId: '1037434767632',
    projectId: 'mashiso-c06d3',
    storageBucket: 'mashiso-c06d3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDpUbhms7txVIwR9zyVIj7XS_-wJvcUP9c',
    appId: '1:1037434767632:ios:1f17113d6bc048c1ae7d95',
    messagingSenderId: '1037434767632',
    projectId: 'mashiso-c06d3',
    storageBucket: 'mashiso-c06d3.appspot.com',
    iosClientId: '1037434767632-ikdicvptinmuenctuk3sit9rdihhlgrl.apps.googleusercontent.com',
    iosBundleId: 'com.Mashiso.',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDpUbhms7txVIwR9zyVIj7XS_-wJvcUP9c',
    appId: '1:1037434767632:ios:cd8bfc285477ac63ae7d95',
    messagingSenderId: '1037434767632',
    projectId: 'mashiso-c06d3',
    storageBucket: 'mashiso-c06d3.appspot.com',
    iosClientId: '1037434767632-fmeoqmr5g9lq4ilppfqr1lv6d072bqq6.apps.googleusercontent.com',
    iosBundleId: 'com.macOS',
  );
}
